### ISSUE TITLE
Problemas ao usar Transactions

### ISSUE THREAD

**Issue by flemej** [hxphp/hxphp#149]
Olá, pessoal!
Estou tentando trabalhar com transactions mas quando tento utilizá-las, acontece o seguinte erro:
'SyntaxError: Unexpected token run(  )...\index.php:55
30.42332208408call_user_func_array:{C:\wamp64\www\EVS\src\HXPHP\System\App.php:109}
( ???, ??? )...\App.php:109
40.42332208472SaleController->insertSaleAction(  )...\App.php:109
50.44412323104Sale::insertSale( ??? )...\SaleController.php:39

Segue fragmento do meu código que está no model Sale:

            try {

                $transactionSale = self::connection();
                $transactionSale->transaction();
                $insertSale = self::create($dados);

                if ($insertSale->is_valid())
                {
                    $callBackObj->errors = 'none';
                    $post["sale_id"] = $insertSale->id;
                    $insertSaleProducts = SalesProduct::insertSaleProducts($post);
                    if (!$insertSaleProducts->status)
                    {
                        $callBackObj->errors = $insertSaleProducts->errors;
                    }

                    if ($insertSaleProducts->status && intval($post['payment_option_id']) === 88)
                    {
                        $insertSaleInstallments = SalesInstallment::insertSaleInstallment($post);
                        if (!$insertSaleInstallments->status)
                        {
                            $callBackObj->errors = $insertSaleInstallments->errors;
                        }
                    }

                    if ($callBackObj->errors == 'none' && $post['total_amount'] !== $post['total_paid'])
                    {
                        $insertDebitCredit = SaleDebitCredit::insertDebitCredit($post);
                        if (!$insertDebitCredit->status)
                        {
                            $callBackObj->errors = $insertDebitCredit->errors;
                        }
                    }

                    if ($callBackObj->errors == 'none')
                    {
                        $transactionSale->commit;
                        $callBackObj->status = true;
                    }
                    else
                    {
                        $transactionSale->rollback();
                    }
                }
                else
                {
                    $callBackObj->errors = $insertSale->errors->get_raw_errors();
                }
            } catch (Exception $ex) {
                $callBackObj->errors = 'Exception:' . $ex;
            }
Quando retiro os comandos, tudo acontece normalmente. O que pode ser? Tem algo errado?
Muito obrigado!

**Comment by brunosantoshx** [comment]
Olá grande @flemej, tudo bem?

Conseguiu encontrar o problema? Como resolveu essa situação?

A mensagem de erro está acusando `SyntaxError`, portanto, fica difícil analisar sem a visão geral do repositório.

De toda forma, uma das maneiras mais comuns de debugar é usar breakpoints, isto é, você vai adicionando logs ao decorrer do código com numeração crescente e assim consegue determinar até que parte o código rodou. Pode ser alguma classe de log ou até mesmo `print_r` ou `var_dump` para indicar em qual parte o código está parando.

Pretendo adicionar em breve ao framework algum recurso nativo para gerar logs, inclusive. 

Forte abraço e sucesso sempre!

**Comment by flemej** [comment]
Olá, Bruno!
Estou afastado das atividades de desenvolvimento. Quando possível irei
tentar fazer um debug melhor e posto o resultado aqui.
Obrigado e um abraço!

Em sex, 2 de mar de 2018 17:08, Bruno Campos Santos <
notifications@github.com> escreveu:
