### ISSUE TITLE
Problemas no login

### ISSUE THREAD

**Issue by wtcosta** [hxphp/hxphp#153]
Primeiramente quero parabenizar pelo frame, muito bom mesmo.
Segui seu curso de sistema de login completo com o HXPHP e fiz algumas alterações, no meu ambiente local funciona perfeitamente porém quando subo pro servidor de produção a parte de login não funciona, quando coloco $this->auth->redirectCheck() ele fica redirecionando direto para o login, como se não armazenasse a sessão do login. Pode me ajudar?

**Comment by brunosantoshx** [comment]
Olá @wtcosta, tudo bem?

Qual versão do framework você está usando?

Seu código está semelhante ao repositório da série?

Fico no aguardo.
Forte abraço e sucesso sempre!
