### ISSUE TITLE
Alert Template

### ISSUE THREAD

**Issue by lucassousa25** [hxphp/hxphp#154]
Tenho uma dúvida em relação ao **Alert helper**.
Se no casou implementar no meu projeto ou tipo alert (ex.: *sweetalert*), como faria para integrar ao **Alert helper**?
Teria como eu criar um arquivo *.js* que serviria como um template. Há alguma possibilidade?

Desde já agradeço!

**Comment by skay1994** [comment]
No caso para o sweetalert ele é um código javascript, entao você precisa editar o template com um codigo javascript dentro da tag script para rodar quando a pagina for carregada. O arquivo que vai precisar alterar é o https://github.com/brunosantoshx/hxphp/blob/master/templates/Helpers/Alert/alert.html

```html
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="application/javascript">
    swal("%s", {
        buttons: ["botao 1", "botao 2"],
    });
</script>
```
Usando o conjunto caracters "%s" é aonde vai colocar o texto que vai ser inserido via php pela funcao de carregamento, como é no template padrão. Lembrando que vai precisar colocar esse conjunto de caracteres em todos os locais que vao precisar de substituição.

**Comment by lucassousa25** [comment]
Ok! Serviu, porém surgiram outras dúvidas.
- Como ficaria no alert-list.html?
- Se caso tivesse dois erros, iria renderiza-los no sweetalert?
- Eu poderia trocar o endereço remoto <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> por um local pelo BOWER?

**Comment by skay1994** [comment]
Pode trocar o link do script, tirar ele do template e colocar no html principal, nao precisa manter ele junto ao template, mais precisa ter ele carregado na pagina.

E quanto ao alert-list, o sweetalert nao tem nenhum modelo no site de notificação com corpo muito grande, porem olhando a documentação, acho que isso pode funcionar montando a string da forma correta para usar. 

Novamente nao testei, porem se nao funcionar nao acho que teria uma forma de varios erros usando o sweetalert 

```html
<script>
    swal({
        title: "Here's a title!",
        button: ["Coolio","Coolio 2"],
        content: 'conteudo_aqui'
    });
</script>
```

**Comment by lucassousa25** [comment]
Tirei o `<li>` pois dentro do script ele funciona como um string normal. Não sei como formatar isso dentro do script.

> ```
> <script type="application/javascript">
> 	swal({
> 		type: "%s",
> 		title: "%s",
> 		text: "%s",
> 		confirmButtonClass: "btn-default",
> 		confirmButtonText: "OK!",
> 		closeOnConfirm: true
> 	});
> </script>
> ```

Estou usando o bootstrap-sweetalert. 

![side-alert](https://user-images.githubusercontent.com/32560743/35334926-208b9466-00fb-11e8-8850-4e9779fbab44.png)

**Comment by skay1994** [comment]
Se não funciona tags html, pode tentar usar caracteres como ```\n``` sao caracteres usado para quebra de linha, nao sei, achei essa pg no stackoverflow sobre https://stackoverflow.com/questions/1155678/javascript-string-newline-character

**Comment by brunosantoshx** [comment]
Olá @lucassousa25 e @skay1994, tudo bem?

Deu tudo certo? 

É como o @skay1994 disse: Você pode customizar os templates para usar códigos JAVASCRIPT também, porém, é importante mover o `echo $this->alert;` para um local mais apropriado. A inclusão das dependências pode ser feita usando o `Bower` e somente o código de exibição iria no template.

Dependendo de como ficou, podemos até formular um helper nativo pra isto.

Forte abraço e sucesso sempre!
