### ISSUE TITLE
Abrindo JSON ao invés do Controller

### ISSUE THREAD

**Issue by Lesnock** [hxphp/hxphp#155]
Eu encontrei algo que me intrigou durante a programação.
Substituindo o nome do Controller na URL, pelo nome de um arquivo JSON que esteja na pasta raiz do projeto, o navegador (Chrome) irá exibir este arquivo ao invés de chamar o Controller, e no caso do Internet Explorer, irá baixar o arquivo JSON.

Por exemplo, se eu digitar na URL:
_http://localhost/HXPHP/Usuarios_

E houver um arquivo Usuarios.json na pasta raiz, o navegador irá chamar o arquivo JSON ao invés de abrir o Controller Usuários.

Algo como:
_http://localhost/HXPHP/Composer_

Faz com que meu arquivo Composer.json seja exibido.

Isso não é ruim?
Será que há como bloquear esse comportamento?

Muito obrigado!

**Comment by skay1994** [comment]
Você ta usando qual versão? e fez alguma modificação na base do framework?

**Comment by Lesnock** [comment]
@skay1994 
Minha versão é a **3.0.0-rc.4**, mas também com a versão atualizada e sem nenhuma modificação.
Se eu acessar:

_http://localhost/hxphp/Composer_
O arquivo Composer.json é simplesmente exibido pelo navegador.

Acredito que seja necessária alguma configuração no .htaccess.

**Comment by skay1994** [comment]
estranho, usando a ultima versão, recém baixada da erro 404. vou tentar com a versão 3.0.0-rc.4

![image](https://user-images.githubusercontent.com/5720296/36430416-e576defa-1633-11e8-8e96-e7cb5c12364b.png)

**Comment by skay1994** [comment]
Não consegui reproduzir o problema nem com a versão **3.0.0-rc.4**

**Comment by Lesnock** [comment]
@skay1994 
Você chegou a tentar pelo Chrome?

**Comment by skay1994** [comment]
@Lesnock não tinha testado, agora testei com o Chrome e o Edge para ter certeza a todos mostra o erro padrão de não encontrado.

De qualquer forma, chequei o código do framework e ele vai buscar por um controller "Composer", isso se o apache nao redirecionar, mais isso vai depender do .htaccess e nao do framework

**Comment by brunosantoshx** [comment]
Olá @Lesnock e @skay1994, tudo bem?

É como o @skay1994 disse: Este não é o comportamento padrão, ou seja, primeiro existe o sufixo obrigatório `Controller` e depois as condicionais de existência do respectivo arquivo, portanto, é de se esperar que alguma configuração do Apache esteja resultando neste comportamento.

De toda forma, acho muito importante investigarmos de perto este comportamento. Poderia postar o conteúdo do seu arquivo `.htaccess` aqui e também nos confirmar se fez alguma edição nos arquivos de configuração do Apache?

Fico no aguardo.
Forte abraço e sucesso sempre!

**Comment by Lesnock** [comment]
@brunosantoshx, @skay1994 
Sim Bruno, não há como ser o HXPHP que esteja fazendo isso.
Testei em diferentes computadores, com diferentes projetos, e em todos obtive o mesmo resultado.
Tentei inclusive reinstalar o WAMP e clonar o HXPHP novamente para começar um projeto do zero, mas mesmo assim continua exibindo o arquivo JSON.

![image](https://user-images.githubusercontent.com/19783675/36941836-10cada4e-1f43-11e8-868f-8445fcbd9dfa.png)

Segue abaixo o código do meu `.htaccess`:
```
Options +FollowSymLinks
Options -Indexes

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /hxphp/
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /hxphp/index.php [L]
</IfModule>

<Files ~ "^\.(htaccess|htpasswd)$">
    deny from all
</Files>

<IfModule mod_deflate.c>
    <FilesMatch "\.(js|css|jpg|png|gif|ico|php|html|htm)$">
        <ifModule mod_filter.c>
            SetOutputFilter DEFLATE
            AddOutputFilterByType DEFLATE text/css text/javascript application/x-javascript text/html text/plain text/xml image/x-icon
        </IfModule>
    </FilesMatch>
</IfModule>
```
