### ISSUE TITLE
HXPHP 3 - Diretório SRC não existe mais?

### ISSUE THREAD

**Issue by jfcnetto** [hxphp/hxphp#157]
Boa tarde bruno, no vídeo #2 - Instalando e configurando o HXPHP + Modelagem de banco de dados menciona para as configurações o diretorio src, porem baixei hxphp aqui no git e não existe mais este direorio qual seria o procedimento?

**Comment by skay1994** [comment]
Foi feita recentemente uma mudança na estrutura do framework referente aqui no repositório, para simplificar atualização de projetos existentes. 

Agora a base do framework tem seu próprio repositório. sendo que é necessário só copiar os arquivos desse repositório em uma futura atualização. https://github.com/HXPHP/framework

Para continuar usando o framework você pode criar as pastas do aplicativo na base do framework e vai ser funcional,

**Comment by brunosantoshx** [comment]
Olá @jfcnetto e @skay1994, tudo bem?

É como o @skay1994 disse: O HXPHP foi reestruturado neste major update e agora é uma dependência do Composer, isto é, você instala e atualiza o framework com os comandos do Composer.

São dois projetos diferentes:
`hxphp/framework`: Core do framework;
`hxphp/hxphp`: Aplicação (Models, Controllers, Views, Assets, Templates e arquivos estáticos).

Antigamente para atualizar o framework era preciso copiar a pasta `src` atualizada e sobrescrever a antiga, mas, agora isso é feito automaticamente rodando o comando:  `composer update`.

Foi um enorme progresso para tornar o desenvolvimento ainda mais seguro e prático. 

Espero que tenham gostado.
Forte abraço e sucesso sempre!

PS: Pretendo atualizar as aulas mostrando a nova forma de trabalhar com o HXPHP em breve.

**Comment by brunosantoshx** [comment]
Outra novidade @skay1994 é que vamos poder fazer o mesmo com os módulos para HXPHP em breve. 

Isto é, ao invés do usuário copiar as pastas e fazer tudo manualmente, ele só vai precisar:

+ Rodar um comando: `composer require hxphp/facebook-login`;
+ Adicionar o provider (registrar o módulo) no `app/config.php`;
+ Definir as configs do módulo.

Se quiser saber mais:

https://blog.jgrossi.com/2013/creating-your-first-composer-packagist-package/

Abração!
