### ISSUE TITLE
Erro de instalação via composer

### ISSUE THREAD

**Issue by skay1994** [hxphp/hxphp#159]
A instalação via composer resulta no erro da imagem abaixo
![image](https://user-images.githubusercontent.com/5720296/37064583-4f9f9fd0-217c-11e8-91ba-3e4cb35710b5.png)

Porem mesmo com o erro o framework é instalado de forma normal e é funcional

@brunosantoshx aproveitando esse issue, quero saber se a equipe do hx tem algum meio de comunicação.

**Comment by brunosantoshx** [comment]
Oi @skay1994, tudo bem?

Foi um erro temporário n Packagist/Github, creio eu. Agora está normalizado. 

Forte abraço e sucesso sempre!
