### ISSUE TITLE
Conexão com DB em ambiente de produção

### ISSUE THREAD

**Issue by EmersonRomao** [hxphp/hxphp#161]
Olá @brunosantoshx , td bem com vc?

Desenvolvi um sistema e nele faço uso do Framework HXPHP, mas ao subir para o meu ambiente de produção, me deparei com a seguinte mensagem: 
![image](https://user-images.githubusercontent.com/13119980/37175186-87661350-22f7-11e8-8b3e-69bad9c760b9.png)
Por favor, poderia me ajudar? Desde já agradeço,
Abraço

**Comment by EmersonRomao** [comment]
Bom dia @brunosantoshx , td bem?

Descobri que o comando **parse_url** que está na **linha 181** do arquivo **Connection.php** apontado pelo error retorna um **bool(false)**, na verdade ele teria que retornar um array contendo as variáveis da connection string.
Segundo a documentação do PHP, se um dos elementos da connection string não estiver presente, não será criada uma entrada para ele.
Teria uma solução prática para esse problema? Já encontrou esse erro antes?
Obrigado

**Comment by skay1994** [comment]
@EmersonRomao no caso, esse arquivo citado faz parte do php-activerecord que é uma dependência do hxphp para manusear o db, para esse problema seria necessário criar uma issue no repositório dele.

Porem ja usei o hxphp em produção por um tempo e não cheguei a ter esse erro. poderia informar as configurações que esta usando tanto no hxphp quanto a do servidor.

**Comment by EmersonRomao** [comment]
Boa noite @skay1994 , desde já agradeço pela ajuda, ah e obrigado pelo toque a respeito do repositório do **php-activerecord**, me ajudou bastante. Bom descobri que o problema estava na configuração, mais especificamente no elemento **password** da connectionstring. Neste parâmetro continha o caractere especial #. Resolvi testar o comando de decodificação de URL **urldecode** e com isso consegui conectar a minha aplicação no banco de dados. Em todo o caso, o quadro atual é que acabei gerando uma nova senha para o banco e removi o comando porque não achei necessário e neste momento a aplicação e o banco de dados estão funcionando bem.
