### ISSUE TITLE
Erro HTTPS

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#163]
Bruno bom dia!

Como resolvo este problema abaixo?

Notice: Undefined index: HTTPS in C:\xampp\htdocs\latam\vendor\hxphp\framework\src\HXPHP\System\Configs\GlobalConfig.php on line 27

no arquivo:

  if (array_key_exists('HTTP_HOST', $_SERVER)) {
            $https = $_SERVER['HTTPS'];   =======>>> linha 27

            $this->site->protocol = ($https && 'off' != $https) ? 'https' : 'http';
            $this->site->host = $_SERVER['HTTP_HOST'];
            $this->site->url = $this->site->protocol.'://'.$this->site->host;
        }

**Comment by skay1994** [comment]
Ja localizei o erro e enviei uma atualização, execute o comando ``` composer update ```
