### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#164]
Gostaria de saber se poderíam me orientar como encontrar na documentação uma forma de criar 2 templates de acesso para um sistema que estou iniciando, o sostema basicamente seria um site no qual teria algumas áreas como notícia, galeria de imagens e vídeos, porém, este itens teriam
Um layout padrão de header e footer.

So que tenho que criar a área administrativa destes itens, o qual teria outro template de header e footer, poderia me exemplificar como poderia fazer isso utilizando o hxphp!?

Obrigado!

**Comment by skay1994** [comment]
Você pode criar uma classe para extender o controller e no construtor colocar a base de template para que na action você so configure o arquivo da view, se ouver necessidade. Veja abaixo como fazer:

Primeiro altere o arquivo ```composer.json``` para que faça o auto load das novas classes. Adicione esse novo pedaço ao seu arquivo.

```json
"autoload": {
  "psr-4": {
       "App\\": "app/"
   }
},
```
Um Exemplo de arquivo ja editado.
```json
{
    "name": "hxphp/hxphp",
    "description": "HXPHP - O seu primeiro framework.",
    "type": "project",
    "homepage": "http://www.hxphp.com.br/",
    "keywords": ["framework", "hxphp"],
    "license": "MIT",
    "require": {
        "php": ">=7.0.0",
        "hxphp/framework": "dev-master"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "authors": [
        {
            "name": "Bruno Campos Santos",
            "email": "bruno@plug.ag",
            "role": "Developer"
        }
    ],
    "support": {
        "issues": "https://github.com/hxphp/framework/issues",
        "wiki": "https://github.com/hxphp/docs"
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "config": {
        "discard-changes": "stash",
        "optimize-autoloader": true
    }
}
```
Após essa configuração execute o comando ```composer dump-autoload```

Depois de executar o comando crie essa estrutura de pasta dentro da pasta app:
app ==>system ==> controller

Crie agora uma classe para representar o frontend e no contrutor defina o arquivo de header e footer que serao usados.

```php
<?php

namespace App\System\Controller;

use HXPHP\System\Configs\Config;
use HXPHP\System\Controller;

class FrontendController extends Controller
{
    public function __construct(Config $configs = null)
    {
        parent::__construct($configs);

        $this->view
            ->setHeader('header')
            ->setFooter('footer');
    }
}
```
E crie outra classe para representar o backend.

```php
<?php

namespace App\System\Controller;

use HXPHP\System\Configs\Config;
use HXPHP\System\Controller;

class BackendController extends Controller
{
    public function __construct(Config $configs = null)
    {
        parent::__construct($configs);

        $this->view
            ->setHeader('backend/header')
            ->setFooter('backend/footer');
    }
}
```
Depois é so estender essas novas classes em seus controllers.

```php
<?php

use App\Controller\BackendController;

class IndexController extends BackendController
{
}
```

**Comment by antoniokarlos** [comment]
Muito obrigado, me ajudou demais!!!

Em 28 de março de 2018 21:31, Jorge Carlos <notifications@github.com>
escreveu:

**Comment by antoniokarlos** [comment]
Jorge poderia me tirar outra dúvida neste caso?

Quando eu faço esse processo que me explicou e que está funcionando como eu
devo proceder no caso para pegar na controller as informações:
'''
$user_id = $this->auth->getUserId();
$user = User::find($user_id);
$role = Role::find($user->role_id);
'''

Por que o método __contrutor está na controller Backend, se eu coloco este
código na BackendController, ela não encontra o User::find();


2018-03-28 23:14 GMT-03:00 Jorge Carlos <notifications@github.com>:

**Comment by skay1994** [comment]
Cheque primeiro se o modulo auth ja foi carregado e configurado, uma dica pra isso é colocar o trexo de configuração do modulo ja no construtor da classe Backend.

E como ja vai ter no escopo a variavel de configuração, pode usar ela mesmo para poder passar as configurações.

```php
<?php

namespace App\Controller;

use HXPHP\System\Configs\Config;
use HXPHP\System\Controller;

class BackendController extends Controller
{
    public function __construct(Config $configs = null)
    {
        parent::__construct($configs);

        $this->load('Services\Auth',
            $configs->auth->after_login,
            $configs->auth->after_logout,
            true,
            $this->request->subfolder
        );

        $user_id = $this->auth->getUserId();
        $user = User::find($user_id);
        $role = Role::find($user->role_id);

        $this->view
            ->setHeader('backend/header')
            ->setFooter('backend/footer');
    }
}
```

Sobre a sua formatação de codigo. Para iniciar a formatação use o **Acento Grave ( ` )**, crie 6 caracteres do acento, depios divida em dois grupos de 3 acentos e coloque a linguagem que será o codigo do lado dos 3 primeiros acentos, pule uma linha e digite ou cole o codigo. E feche com os 3 acentos restantes

Ex: Abertura, ta quebrado de proposito para que nao seja convertido em codigo real:
 ` ``php
Ex: Fechamento: ```

Outra coisa, procure mostrar o maximo de codigo para que seja demostrado todo o uso do codigo junto com os problemas. 
Como no exemplo que mandei uma classe inteira ajuda a ter uma melhor leitura do codigo, caso tenha metodos/funcoes que nao fazem parte do problema é so tirar do exemplo, porem tente manter o maximo de informações

**Comment by skay1994** [comment]
pode tirar o ```$this->request->subfolder```, caso nao mude a configuração de subpasta nao precisa usar essa configuração.

Uma dica, realize a leitura dos erros para que consiga resolver seus erros de forma simples e rapida, assim consegue agilidade e uma percepção mais direta do funcionamento do seu codigo.

**Comment by antoniokarlos** [comment]
entendi, é que algumas configurações não consigo identificar na documentação, por exemplo, ao retirar a linha que você colocou na resposta anterior dá o erro de que dentro da pasta em que criamos a controller Backend não existe a model USER porém, não identifiquei na documentação como eu mudo essa localização, tipo se é ali no método ou em outro local.

Veja o erro que está dando agora:

E quando eu removo a subpasta apresenta o seguinte erro:

Fatal error: Uncaught Error: **Class 'App\System\Controller\User' not fou**nd in C:\xampp\htdocs\latam\app\system\controller\BackendController.php:24 Stack trace: #0 C:\xampp\htdocs\latam\vendor\hxphp\framework\src\HXPHP\System\App.php(101): App\System\Controller\BackendController->__construct(Object(HXPHP\System\Configs\Config)) #1 C:\xampp\htdocs\latam\index.php(56): HXPHP\System\App->run() #2 {main} thrown in C:\xampp\htdocs\latam\app\system\controller\BackendController.php on line 24
