### ISSUE TITLE
Importação, criação e leitura de arquivos de planilhas

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#165]
Gostaria de saber, se há algum modelo de importação de planilha utilizando o HXPHP?

Algum método implementado, ou algo do tipo?

Obrigado, estou conseguindo evoluir no desenvolvimento com o HXPHP... vocês estão de parabéns!

**Comment by skay1994** [comment]
No HXPHP não tem nenhum modo de usar arquivos de planilha por padrão no framework, porem você pode usar outros pacotes para completar essa finalidade, por exemplo o [PhpSpreadsheet ](https://phpspreadsheet.readthedocs.io/en/develop/) é uma otima ferramenta para criar e ler planilhas, caso ela nao trabalhe com o formato que precisa, procure no google por alguma outra ferramenta.

Em relação ao titulo da issue, procure criar titulos que facilite o entendimento do problema, assim seu problema sendo resolvido, o proximo que procurar sobre o assunto ja vai ter a issue criada e respondida, assim evita duplicidade nas issues do framework.
