### ISSUE TITLE
Erro ao Criar um novo Model para Listar

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#166]
Gostaria de uma ajuda, estou com o seguinte problema:

Estou fazendo um sistema administrativo de notícias, porém não obtive sucesso, gostaria de saber se poderiam me ajudar a identificar onde errei no processo:

1) Criei uma tabela chamada news(neste mesmo formato de escrita)
2) Criei uma Model chamada New e ela está assim:
<?php

class New extends \HXPHP\System\Model
{

}

3) Criei Controller:
 public static function newsAction(){
    	
    	$this->view
        	   ->setPath('admin/news')
               ->setFile('index')
               ->setHeader('headerAdmin')
               ->setFooter('footerAdmin') 
               ->setTemplate(true)
              ->setVars([
                'news' => New::all()
              ])
               ->setTitle('Administrativo');
    }

4) Criei minha view, porém na linha de cerificação do if da o erro abaixo:

Linha do IF ---->>>  <?php if ($view_news) : ?>

Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)  --> essa linha refere-se a linha do item 3 ->setVars([

Poderiam me dar a dica do que eu estou fazendo errado?

**Comment by skay1994** [comment]
Provavelmente o erro é relacionado a palavra reservada "New", antes de criar classes e funções cheque essa lista para evitar problemas de palavras reservadas.

[Lista de palavras reservadas PHP](https://secure.php.net/manual/pt_BR/reserved.php)

Mais uma coisa, use a formatação de codigo do github, facilita tanto a nossa leitura quando a vc se expressar melhor no seu problema.

[Formatação de codigos Github](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)

**Comment by brunosantoshx** [comment]
Fala @antoniokarlos e @skay1994, tudo bem?

É exatamente como o @skay1994 comentou, isto é, existem algumas palavras reservadas que não podem ser usadas para nomear classes. A palavra `new` é uma delas. 

Acima de tudo, o objetivo de colocar no singular não consiste em apenas remover os `s` ao final dos nomes no plural, isto é, a palavra `news` significa notícias, certo? A palavra `new` significa **novo**. Nesse caso o certo seria manter `news` mesmo.

Forte abraço e sucesso sempre!
