### ISSUE TITLE
Campo com tag html

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#167]
Olá tenho um CRUD de notícia em meu sistema e no form tem um campo de editor de texto html no qual é possível formatar o texto pelo usuário.

Quando eu faço a inclusão ou o Update ele remove as tags html deste campo, tem como eu colocar específicamente neste campo uma regra para aceitar tag html?

Obrigado!

**Comment by antoniokarlos** [comment]
@skay1994  @brunosantoshx  poderiam me dar um help neste caso??

Agradeço desde já!

**Comment by skay1994** [comment]
Me desculpe a demora, dei uma pesquisada antes, acabei q nao achei um modo de impedir a limpeza da string por meio do INSERT e UPDATE usando os modos normais do PHP Active Records, porem vc pode pegar uma instancia do PDO e escrever manualmente essa query em expecifico.

Eu pessoalmente não saberia como ajudar, porem o @brunosantoshx tem um conhecimento mais aprofundado do PHP Active Records e deve conseguir te ajudar, porem ele esta indisponível a um tempo e não sei quando ele poderá oferecer suporte.

**Comment by antoniokarlos** [comment]
Você saberia me dizer como fazer para pegar uma instância PDO como disse na sua resposta?

Pelo menos por onde começar??

Ta difícil, preciso concluir esta parte!

**Comment by brunosantoshx** [comment]
Olá @antoniokarlos e @skay1994, tudo bem?

Na verdade, esta é uma configuração padrão de segurança do HXPHP para evitar ataques XSS. É extremamente importante tomar cuidado com a escrita de HTML no banco de dados, pois, é difícil restringir quais tags serão ou não aceitas sem falar de brechas como aatributos `onerror, onload e etc` que permitem a execução de JS mesmo em tags aceitas.

Sem falar da codificação em hexadecimal e etc. De forma que o browser consiga interpretar, mas, você talvez não preveu na validação.

Se for mesmo seguir com a escrita de HTML recomendo encontrar algum pacote legal AntiSamy (proteção contra XSS).

Para permitir é só adicionar este código no método do controller:

```php
$this->request->setCustomFilters([
            'nomedocampo'    => [
                'filter' => FILTER_UNSAFE_RAW,
            ]
        ]);
``` 

https://hxphp.github.io/docs/2.0/http.html

Forte abraço e sucesso sempre!
