### ISSUE TITLE
Ajuda na migração para o servidor

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#169]
@brunosantoshx  ou @skay1994 

Poderiam me ajudar nesta mensagem que apareceu quando eu fui publicar meu sistema no servidor:

'''
O suporte ao PHP 5 terminou e o repositório agora encontra-se compatível com o PHP 7.1.
Para continuar com PHP 5 use: https://github.com/brunosantoshx/hxphp/releases/tag/v2.18.14 ou atualize seu PHP para a versão: 7.1.0 ou superior.
Se você optar por atualizar o PHP lembre-se de atualizar todas as dependências através do Composer.
'''

Como devo proceder neste caso? Pois, ví que nesta versão a pasta é diferente, poderiam me dar um help?

Obrigado!

**Comment by skay1994** [comment]
No caso você consegue saber qual versão esta rodando do framework verificando se a pasta src existe, na versão para PHP 5.6 ela ainda esta presente, e na versão para PHP 7.1 ela não existe e o framework é uma dependencia via composer.

**Comment by flemej** [comment]
Olá, Antônio!
A versão do php disponível na sua hospedagem está setada para 5.0. Algumas
hospedagens free (não sei se é o seu caso) disponibilizam somente o PHP 5.
Em outras, isso é configurável pelo painel de controle da própria
hospedagem. Verifique com o seu provedor a possibilidade de modificar a
versão atual.

Em ter, 3 de abr de 2018 14:47, Antonio Carlos <notifications@github.com>
escreveu:

**Comment by antoniokarlos** [comment]
Entao,

O problema é que no server está rodando outra aplicação php que não sei se terá algum problema se migrar para 7.0, como eu fiz o programa todo dentro do hxphp, vocês teriam uma sugestão rápida de como eu poderia dar um downgrade na versão do php!?

Fico no aguardo!
Obrigado

Enviado do meu iPhone

Em 3 de abr de 2018, à(s) 16:10, Fabio LJ <notifications@github.com> escreveu:

**Comment by skay1994** [comment]
Lembrando que é PHP 7.1, e quanto a isso depende muito da sua aplicação atual, se ela suporta ou nao, faz um teste em uma versão local da aplicação e roda ela no PHP 7.1 para ter certeza.

Outra coisas grandes projetos que são compatíveis com php 5.6 funcionam usando o php 7 porem sem usar as novidades inseridas na nova versão.

Quanto ao proprio HXPHP você pode rever o codigo que ja escreveu comparando com a versão anterior para checar o funcionamento, usando a nova versão fica inviável rodar abaixo do PHP 7 pois ela usa o novo conceito de declaração de tipagem nos métodos e funções.

**Comment by antoniokarlos** [comment]
Jorge, agradeço sua atenção, mas acredito que nós confundimos no processo...

Eu estou usando a última versão do hxphp, ou seja a versão 7.1 do php, certo!?

Quando eu fui subir o projeto no servidor, apareceu a mensagem de que se for para rodar php 5 eu teria que usar a versão 2.48 se eu não me engano.

Aí foi que eu fiquei em pânico, como eu faço isso!? Depois de ter feito tudo na versão 3.0!

Meu maior medo é falar para o cliente fazer o upgrade para o php 7.1 no qual a empresa cobra pra fazer isso e a aplicação que eles usam lá pare de funcionar entendeu!?


Enviado do meu iPhone

Em 3 de abr de 2018, à(s) 19:09, Jorge Carlos <notifications@github.com> escreveu:

**Comment by skay1994** [comment]
Ha sim, entendi, normalmente a hospedagem fornece um meio de trocar a versão do php atravez do arquivo .htaccess e com isso você pode usar o HXPHP 3 em um subdomínio ou em uma subpasta. 

Caso não seja possível dessa maneira, baixe o HXPHP 2 e coloque sua pasta app do 3 nele, e veja se os recursos que uso são compatíveis, não existe mtas mudanças no uso básico do framework entre o 2 e o 3, porem isso vai levar um tempo para adaptar os códigos para funcionarem. Compare as duas documentações e veja as diferenças que vai precisar mudar no seu código.

**Comment by antoniokarlos** [comment]
Jorge, consegue me tirar outra dúvida?

Tenho um de CRUD de notícias, no qual preciso ter um campo de input de
html, porém o sistema está removendo as tag html, tem alguma forma de
específicamente neste campo não remover estas tags?

Obrigado pela ajuda!

Em 4 de abril de 2018 10:58, Jorge Carlos <notifications@github.com>
escreveu:

**Comment by skay1994** [comment]
Deixei uma resposta na issue da sua duvida referente a essa situação, porem essa sua duvida foi devidamente esclarecida?

**Comment by antoniokarlos** [comment]
Jorge, boa noite!

Eu fiz o seguinte, criei um subdomínio e lá apliquei a utilização do php 7 via .htaccess e funcionou.

Agradeço desde já sua prestatividade, estão me ajudando bastante, agora só ficou aquela questão do html mesmo que coloquei na outra issue.

Vou tentar fazer o insert direto pra ver se da certo!

Obrigado!

Enviado do meu iPhone

Em 5 de abr de 2018, à(s) 18:13, Jorge Carlos <notifications@github.com> escreveu:

**Comment by skay1994** [comment]
Muito bom, a troca de versão do php via .htaccess ajuda muito nesses casos e fico feliz por conseguir resolver seu problema!
