### ISSUE TITLE
Anexar arquivo no e-mail

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#170]
Olá, estou precisando anexar um arquivo no envio do e-mail, poderiam me dar uma dica de como devo fazer??

Obrigado!!

**Comment by skay1994** [comment]
A biblioteca padrão de emails do HXPHP não envia com anexos, pode usar o [PHP Mailer](https://github.com/PHPMailer/PHPMailer) que vai te fornecer varias funcionalidades extras.

Tem um exemplo de email simples na propria pagina do PHP Mailer, qualquer coisa ta aqui um link para vc usar. [A Simple Example](https://github.com/PHPMailer/PHPMailer#a-simple-example)

**Comment by antoniokarlos** [comment]
Obrigado Jorge,

Só uma duvida, esse modelo eu posso usar direto na controller ou tenho que criar uma função e colocar lá na pasta de e-mail como no hxphp!?

Eu instalei pelo composer, no caso eu preciso enviar a pasta vendor novamente pro server né!?

Agradeço desde já!

Enviado do meu iPhone

Em 6 de abr de 2018, à(s) 15:44, Jorge Carlos <notifications@github.com> escreveu:

**Comment by skay1994** [comment]
Vai precisar usar por fora, pois depende de um componente que nao faz parte do framework, mais pode colocar no controle sim, porem como nova instancia da biblioteca dentro de seu controller

**Comment by brunosantoshx** [comment]
Fala @antoniokarlos e @skay1994, tudo bem?

Pra usar qualquer pacote externo só é preciso instalar pelo Composer e dar o `use` no namespace do pacote. 

Quando for fazer o deploy para o servidor, você pode tanto enviar a pasta **vendor** como também pode rodar o `composer install` se tiver acesso SSH.

Forte abraço e sucesso sempre!
