### ISSUE TITLE
Session Message

### ISSUE THREAD

**Issue by Lesnock** [hxphp/hxphp#171]
Olá!

Tenho reparado que ao criar uma session com o nome de "message", ela desaparece logo depois que que a página é atualizada.
Na verdade era exatamente o que eu precisava, mas me surgiu uma dúvida:

Onde está escrito esse comportamento dentro do HXPHP?

Obrigado e abraços!

**Comment by Lesnock** [comment]
Olá novamente!
Descobri o que houve!
O Helper Alert também utiliza a session "message", e dentro de sua estrutura há um comando de `clear `desta session.
Isto causou um conflito entre a minha session e a session do Helper Alert.

Não seria melhor colocar algum prefixo no nome da session do Helper Alert?
Algo como: `alert_message` acho que seria o ideal.

Obrigado!

**Comment by skay1994** [comment]
Olá @Lesnock eu andei analisando o código, e  realmente acontece o que você disse e acabo dando um conflito inesperado, vo enviar uma solução, porem eu pensei que se o metodo getAlert não for executado, a mensagem nao deveria ser apagada após a visualização.

**Comment by Lesnock** [comment]
@skay1994 
E apenas alterei o nome da session do Helper Alert para `alert_message` e enviei um Pull Request.
Acredito que essa mudança não resolveria o problema em seu todo, mas tornaria um conflito muito mais difícil de acontecer.

Obrigado pela atenção!

**Comment by Lesnock** [comment]
@skay1994 
Não se esqueça que o método `getAlert` está sendo executado dentro do `__toString`.

**Comment by skay1994** [comment]
Uhum, junto com o seu pull também pode ser melhor gerar uma subseção para os alertas, de forma a poder incluir mais de um alerta, e também incluir um método para escolher a permanência ou não de algum alerta em especifico
