### ISSUE TITLE
GetRelativeURL não usa o caminho certo

### ISSUE THREAD

**Issue by Lesnock** [hxphp/hxphp#172]
Olá!

Tenho uma `Action` que utiliza uma view de outra pasta, e quando tento usar o método `$this->getRelativeURL()`, ao invés dele concatenar o nome do Controller atual, ele concatena o nome da pasta onde está a view que utilizo.

Acredito que o método deve ser refeito.

Obrigado!

**Comment by skay1994** [comment]
pode mostrar o codigo de sua view, e como você ta chamando ela no navegador

**Comment by Lesnock** [comment]
O código da view é:

```php
public function addSetAction()
    {
        $this->view->setPath('blank');
        $this->view->setFile('blank');
    }
```

Porém, se eu tento usar:
```php
$this->redirectTo($this->getRelativeURL('adicionar'));
```
Ele me redireciona para:
`http://localhost:8080/BASE/blank/adicionar`

**Comment by skay1994** [comment]
Bem, primeiramente, olhe que o código do redirectTo ja usa o getRelativeURL, com isso, acredito que o uso das duas funções juntas causando a falha na url final.

```php
/**
     * Método que retorna o caminho relativo.
     *
     * @param string $URL        Geralmente a action e parâmetros
     * @param bool   $controller Define se o controller também será retornado
     *
     * @return string Link relativo
     */
    public function getRelativeURL(string $URL, bool $controller = true): string
    {
        $path = true === $controller ? $this->view->path.DIRECTORY_SEPARATOR : $this->view->subfolder;
        return $this->configs->baseURI.$path.$URL;
    }
    /**
     * Redirecionamento.
     *
     * @param string $URL        Link de redirecionamento
     * @param bool   $external   Define se o redirecionamento será relativo ou absoluto
     * @param bool   $controller Define se o controller também será retornado
     */
    public function redirectTo(string $URL, bool $external = true, bool $controller = true)
    {
        $URL = false === $external ? $this->getRelativeURL($URL, $controller) : $URL;
        return $this->response->redirectTo($URL);
    }
```

E como pode ver no código do método. ele por padrão ja busca adicionar o controller na url. Não usando o metodo getRelativeURL ja que ele ja esta presente na funcão para usar quando for link interno.

```php
$this->redirectTo('adicionar'); //http://localhost:8080/controller/adicionar
```

**Comment by Lesnock** [comment]
Hmm!
Faz sentido! Assim funciona perfeitamente!
Aparentemente o método redirectTo foi alterado, e eu não tinha percebido.

Obrigado!
