### ISSUE TITLE
Erro no Serviço Auth

### ISSUE THREAD

**Issue by lucassousa25** [hxphp/hxphp#173]
Tenho vários _Controllers_ no meu projeto mais por algum motivo que não conheço um _Controller_ exibe esse erro mesmo tendo a mesma estrutura dos outros.

No caso quando eu dou um _git clone_ do meu projeto pra outro computador sempre dá esse erro, mas no PC que desenvolvi pela primeira vez esse código funciona normalmente.

Desde já agradeço pela ajuda.

**O Erro que exibe na tela está abaixo.**

Notice: Trying to get property of non-object in C:\xampp\htdocs\sistema_side\app\controllers\VendaController.php on line 11

Notice: Trying to get property of non-object in C:\xampp\htdocs\sistema_side\app\controllers\VendaController.php on line 11

Notice: Trying to get property of non-object in C:\xampp\htdocs\sistema_side\app\controllers\VendaController.php on line 12

Notice: Trying to get property of non-object in C:\xampp\htdocs\sistema_side\app\controllers\VendaController.php on line 12

Fatal error: Uncaught exception 'Exception' with message 'Verifique as configuracoes de autenticacao para a subpasta: < default >' in C:\xampp\htdocs\sistema_side\src\HXPHP\System\Services\Auth\Auth.php:42 Stack trace: #0 [internal function]: HXPHP\System\Services\Auth\Auth->__construct(NULL, NULL, true) #1 C:\xampp\htdocs\sistema_side\src\HXPHP\System\Controller.php(102): ReflectionClass->newInstanceArgs(Array) #2 C:\xampp\htdocs\sistema_side\app\controllers\VendaController.php(14): HXPHP\System\Controller->load('Services\\Auth', NULL, NULL, true) #3 C:\xampp\htdocs\sistema_side\vendor\php-activerecord\php-activerecord\lib\Model.php(779): VendaController->__construct(Array, true) #4 C:\xampp\htdocs\sistema_side\app\models\Sell.php(28): ActiveRecord\Model::create(Array) #5 C:\xampp\htdocs\sistema_side\app\controllers\VendaController.php(89): Sell->cadastrar(Array, 1) #6 [internal function]: VendaController->registraVendaAction() #7 C:\xampp\htdocs\sistema_side\src\HXPHP\System\App.php(106): call_user_func_array(Array, Arr in C:\xampp\htdocs\sistema_side\src\HXPHP\System\Services\Auth\Auth.php on line 42

![erro-controller-side](https://user-images.githubusercontent.com/32560743/39501127-6d77d0f6-4d8f-11e8-93ec-0b9bde380b10.png)

**Comment by skay1994** [comment]
Pelo log que você ta recebendo, esse controller ta com erro nas configurações de autenticação, as variaveis ``` $configs->auth->after_login ``` e ``` $configs->auth->after_logout ``` estão com valor NULL

**Comment by brunosantoshx** [comment]
Olá @lucassousa25 e @skay1994, tudo bem?

Concordo com o @skay1994. Isto é, acredito que você não definiu as configurações no arquivo `app/config.php`. Revise o arquivo e veja se definiu as URLs de redirecionamento.

Forte abraço e sucesso sempre!
