### ISSUE TITLE
Envio de E-mail

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#174]
Gostaria de tirar uma dúvida, estou utilizando o mesmo modelo de envio de e-mail que fez na aula e no sistema, porém tenho identificado que para alguns e-mails as mensagens não chegam e outros casos chegam, é necessário fazer algum ajuste no servidor ou até mesmo no sistema para que as mensagens possam ser enviadas com 100% de certeza que chegará no destinatário?

Obrigado!

**Comment by brunosantoshx** [comment]
Olá @antoniokarlos e @skay1994, tudo bem?

É como o @skay1994 disse: É bem provável que as mensagens estejam caindo em SPAM. Para resolver isto é preciso enviar e-mails autenticados. Você pode usar uma API com Mailgun, por exemplo. Pode usar a API do GMAIL. Ou pode usar um pacote PHPMailer ou SwiftMailer para autenticar via SMTP.

Forte abraço e sucesso sempre!
