### ISSUE TITLE
Problemas ao utilizar $this->request->post

### ISSUE THREAD

**Issue by flemej** [hxphp/hxphp#175]
pessoal, estou me deparando com o seguinte erro ao fazer qualquer $this->request:

( ! ) Fatal error: Uncaught Error: Call to a member function post() on null in C:\xampp\htdocs\EVS\app\views\customer\index.phtml on line 62
--
1 | 0.2823 | 396200 | {main}( ) | ...\index.php:0
2 | 0.3250 | 1410392 | HXPHP\System\App->run( ) | ...\index.php:55
3 | 6.3003 | 2360296 | HXPHP\System\View->flush( ) | ...\App.php:120
4 | 6.3037 | 2399176 | require_once( 'C:\xampp\htdocs\EVS\app\views\customer\index.phtml' ) | ...\Core.php:321

Essa é a linha 62:
`<input type="text" name="name" id="name" placeholder="Nome do cliente" value="<?php echo $this->request->post('name'); ?>">`

A minha versão do HXPHP não é essa nova com docker. Tinha um projeto parado que estou retomando agora então baixei a minha versão do bitbucket e instalei com o composer. Preciso fazer algo diferente?

Sabem o que pode ser?
Obrigado!

**Comment by skay1994** [comment]
No php a variavel $this se refere ao escopo de uma classe, nesse modo que uso não existe o scopo e por isso ela nao é valida, você vai precisar gerar uma variavel usando o metodo setVar veja um exemplo na documentação: https://hxphp.github.io/docs/3.0/views.html#enviando-dados-para-a-view

**Comment by flemej** [comment]
Fala, Jorge!
Tudo bem, parceiro?
Cara, o estranho é que a minha aplicação funcionava... Eu precisei formatar
a máquina e remontei o ambiente mas está dando uns erros malucos. Eu faço o
setvar no Controller e isso já funcionava. Estou tendo problemas também com
o jquery. Os js insistem em não reconhecer o $...
Tudo funcionava, agora....

Em ter, 29 de mai de 2018 00:39, Jorge Carlos <notifications@github.com>
escreveu:

**Comment by flemej** [comment]
Não, Jorge... Essas coisas todas funcionavam... Eu sei como imprimir as
variáveis do php no HTML. Na verdade fiz a pergunta porque sei que coisas
mudaram no framework e, vai ver, tem algo a ver com isso...

Em ter, 29 de mai de 2018 12:01, Jorge Carlos <notifications@github.com>
escreveu:
