### ISSUE TITLE
Método Ajax (Forma Correta de Implementar)

### ISSUE THREAD

**Issue by antoniokarlos** [hxphp/hxphp#177]
@brunosantoshx  boa noite tudo bem!?

Poderia me auxiliar dando alguns exemplos e formas de criar dentro da pasta de controllers uma pasta no qual poderia centralizar meus Arquivos no qual utilizaria com chamada Ajax!?

Pelo que eu entendi, e me corrija se estiver errado, eu não posso criar um metodo Ajax(JsonResult) por exemplo dentro de uma controller. 

Eu fiz um teste desta forma e não funcionou, a única forma que funcionou foi criar uma página php na raiz do projeto no qual passo os parâmetros e faço algumas validações(manuais) para retornar as informações.

Estou aprendendo php, sou desenvolvedor .net e utilizando o .net como exemplo, na controller eu posso criar um método do tipo JsonResult no qual ele permite eu fazer as chamadas Ajax por ele. No hxphp como eu poderia criar isso de forma segura, no qual eu possa utilizar o método construtor para validar autenticação como fazemos na controller!?

Poderia por gentileza colocar alguns exemplos de códigos para que eu possa entender melhor essa parte!?

Obrigado e parabéns pelo framework!

**Comment by skay1994** [comment]
Bom dia @antoniokarlos.

Quanto a separação de controllers por pastas, você vai precisar incluir o nome da pasta na requisição, isso so funciona para um nivel de subpasta, por exemplo:
`http://localhost/hxphp/admin/users/lista`
`http://localhost/hxphp/pasta/controller/action`

Quanto ao **JsonResult**, o framework so vai tratar como **action**  metodos com o prefixo como mostrado na [documentação](https://github.com/hxphp/docs/blob/master/3.0/controllers.md#criando-actions-criando-actions), fora nessa situação, é possivel suar todas as propriedades de uma classe normal dentro de seu controller, como criar um trait com o metodo jsonResult e retornar o resultado.

Outra coisa, na ultima atualização foi iniciada a inclusão do componente symfony Http Foundation no framework, com isso você pode usar o Http Response desse componente para fazer a resposta correta, veja [nesse link](https://symfony.com/doc/current/components/http_foundation.html#response).
