### ISSUE TITLE
Ajuda com input value com $this->request->post('name')

### ISSUE THREAD

**Issue by joaopslorenzo** [hxphp/hxphp#178]
Estou tentando reaproveitar os campos enviados no formulário como na vídeo aula mas está gerando um erro. Alguém poderia me ajudar ?

![campos input](https://user-images.githubusercontent.com/40673937/42056234-0ee5048a-7af0-11e8-8d4b-beaa9dd56268.png)
![erro](https://user-images.githubusercontent.com/40673937/42056236-0f38c02a-7af0-11e8-8ab5-4b04fa58a265.png)

**Comment by skay1994** [comment]
não é possivel usar metodos de classes fora de classes, como você ta na view, é preciso gerar uma variavel a passar para a view com o setVar ou setVars

**Comment by skay1994** [comment]
> Olá skay1994, estou tendo o mesmo problema, poderia me ajudar, onde e como devo adicionar essas variaveis, poderia colocar um exemplo.
> Desde já muito obrigado!

O uso é simples, crie seu controller seguindo a [documentação](https://hxphp.github.io/docs/3.0/controllers.html), 

Aqui um controller basico para listagem de produtos
```php
<?php

class ProdutosController extends \HXPHP\System\Controller
{
    public function indexAction()
    {
        $this->view->setFile('index')
            ->setVar('mensagem', 'Hello World')
            ->setVars([
                    'titulo' => 'Pagina de Produto',
                    'usuario' => 'Bruno Santos',
                    'facebook' => 'https://www.facebook.com/brunocsantos2012'
                     ]);
    }
}
```
Usando a funcao setVar ou setVars, vai ser passado as variaveis com os valores para a view.

Na view vai ser usado assim
```php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $titulo?></title>
</head>
<body>
<h1><?php echo $usuario?></h1>
<span><?php echo $mensagem?></span>
<small><?php echo $facebook?></small>
</body>
</html>

```

**Comment by brunosantoshx** [comment]
Olá @MarckVinny, tudo bem?

Acabei de subir um fix no repositório e atualizei as versões. Será preciso limpar o seu cache do composer usando o comando `composer clear-cache` e depois reinstalar o HXPHP.

Na nova versão, esse bug foi corrigido.

Forte abraço e sucesso sempre!
