### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by hugo7damasceno** [hxphp/hxphp#181]
Não consigo resolver, alguém pode ajudar?

![captura de tela de 2018-07-03 23-16-01](https://user-images.githubusercontent.com/40812887/42253219-199d3e08-7f17-11e8-9cf3-1b3cc1a2e005.png)

**Comment by TMartinns** [comment]
Amigo você precisa abrir o arquivo ".env.example" e salvá-lo apenas como ".env".

**Comment by brunosantoshx** [comment]
Fala galera, tudo bem?

É exatamente como o @TMartinns respondeu! Pra evitar este problema acabei de subir um commit que fará esse processo automaticamente pelo Composer.

Forte abraço e sucesso sempre!
