### ISSUE TITLE
Erro ao conectar ao banco de dados

### ISSUE THREAD

**Issue by lucasarmindo** [hxphp/hxphp#182]
Boa noite, 

Estou tentando conectar ao banco de dados com uma aplicação feita em hxphp, vamos aos fatos:

- localhost, funciona perfeito
- hostinger, **não funciona** ERRO: Database host must be specified in the connection string. If you want to specify an absolute filename, use e.g. sqlite://unix(/path/to/file)
- hostgator, **não funciona** ERRO: Database host must be specified in the connection string. If you want to specify an absolute filename, use e.g. sqlite://unix(/path/to/file)
- locaweb, **não funciona** ERRO: Database host must be specified in the connection string. If you want to specify an absolute filename, use e.g. sqlite://unix(/path/to/file)
- **VPS Locaweb Vazia somente com o mysql 5.7.22 e o sistema em localhost**, **não funciona** ERRO: Database host must be specified in the connection string. If you want to specify an absolute filename, use e.g. sqlite://unix(/path/to/file)

Testei de todas as maneiras, fiz um projeto apenas com um crud para testar a conexão com o banco, coloquei em todas essas a cima e o erro é sempre esse:

ActiveRecord \ DatabaseException
Database host must be specified in the connection string. If you want to specify an absolute filename, use e.g. sqlite://unix(/path/to/file)

Preciso muito de um ajuda nessa parte.

**Comment by skay1994** [comment]
Quanto ao seu problema, é provavel que seu localhost é em Windows, quando se passa para o servidor linux você precisa como na descrição do erro, informar um caminho absoluto para o local do banco de dados em sqlite.

Um teste de exemplo para uso seria contatenar sua string de path com o retorno da constante ``__DIR__``. 

```php
<?php
$path = __DIR__;
$fileDB = '/storage/database/db.sqlite';

$sqlite = 'sqlite://' . $path . $fileDB;
```

**Comment by lucasarmindo** [comment]
Essa modificação seria na aplicação ou eu faria na estrutura do hxphp/php active record?

**Comment by skay1994** [comment]
na sua configuração do app, aonde vc fez a configuração que define aonde fica o arquivo .sql
