### ISSUE TITLE
[PHPUnit] Erro na integração

### ISSUE THREAD

**Issue by TMartinns** [hxphp/hxphp#183]
Estou tendo o seguinte problema ao realizar testes das classes com o PHPUnit, ele simplesmente não consegue encontrar as classes. Eu gostaria de saber como eu posso integrar isso corretamente.

![print](https://user-images.githubusercontent.com/38145497/46321800-cd605980-c5bb-11e8-9c81-84baeafad03b.jpg)

**Comment by skay1994** [comment]
Seu erro é referente ao namespace da classe Diligencia, como ela nao no mesmo diretorio da classe de teste, você vai precisar passar o namespace para usar a classe e seus metodos nos testes

**Comment by TMartinns** [comment]
Eu já testei com o namespace, configurei o autoload do composer, e mesmo assim não encontra a classe. Não tem mais nada que eu possa fazer?

**Comment by TMartinns** [comment]
Eu configurei o autoload do composer dessa forma, ele mapeou tudo certinho, encontrou a classe, mas agora tá dando esse erro com o ActiveRecord.

![print](https://user-images.githubusercontent.com/38145497/46363759-4d350500-c64a-11e8-9da6-94fc7304b65c.jpg)

**Comment by skay1994** [comment]
Parece erro na configuração do banco de dados, seguiu o passo a passo da instalação? https://github.com/hxphp/docs/blob/master/3.0/instalacao-e-configuracao.md#exemplo-de-configura%C3%A7%C3%A3o

**Comment by TMartinns** [comment]
Sim, o sistema já tá até funcional, mas não consigo testá-lo com o PHPUnit.

**Comment by TMartinns** [comment]
@brunosantoshx dá uma força aí Bruno.

**Comment by brunosantoshx** [comment]
Olá @thales-martins, tudo bem?

Não sei se a resposta ainda será útil devido ao longo intervalo que se passou, porém, irei responder aqui da mesma forma. 

O framework atualmente só possui suporte para testes no core, isto é, ainda não existe suporte para testar a aplicação. 

Os procedimentos feitos por você quase que possibilitarão este recurso, porém, faltou o bootstrap do PHPUnit para tudo rodar perfeitamente. 

É necessário um arquivo de bootstrap especialmente feito para testes e que inicie a conexão com o banco e dê o start nos recursos essenciais. 

Sem esse bootstrap, a conexão com o banco não é feita e é por conta disto que apareceu esta mensagem de erro. 

O arquivo seria uma derivação do atual `index.php` com a exceção do método `run()`. É apenas uma teoria e que preciso testar para ter mais certeza.

Mas é algo nessa linha.

Forte abraço e sucesso sempre!
PS: Se conseguiu fazer funcionar, compartilhe com a gente os métodos adotados, por favor.
