### ISSUE TITLE
$this->email->send() sempre retorna false.

### ISSUE THREAD

**Issue by vandersonfabio** [hxphp/hxphp#185]
Olá, gostaria de saber se as atualizações no framework acarretaram mudanças na função de envio de e-mail. Uma vez que a mesma sempre retorna falso.

Já tentei alterar a ordem do 'remetente' e 'email' no array de parâmetro, como também tentei renomear as chaves para 'from_name' e 'from_mail'.
Tentei também passar o parâmetro opcional 'false', mas tudo isso foi sem sucesso.

Utilizei alguns var_dumps no trecho abaixo: 

`$this->load('Services\Email');
                
                $envioDoEmail = $this->email->send(
                    $validar->user->email,
                    'SIGEP ' . $message['subject'],
                    $message['message'] . 'SIGEP',
                    array(
                        'remetente' => $this->configs->mail->from,
                        'email' => $this->configs->mail->from_mail
                    )
                );

                var_dump($validar->user->email); echo "<br>";;
                var_dump($message); echo "<br>";;
                var_dump($this->configs->mail->from); echo "<br>";;
                var_dump($this->configs->mail->from_mail); echo "<br>";;
                var_dump($envioDoEmail); echo "<br>";;`

e os retornos foram:

`string(25) "vanderson.fabio@gmail.com" 
array(2) { ["subject"]=> string(22) "Redefinição de senha" ["message"]=> string(535) "Olá Vanderson Fábio, 
Recentemente você solicitou um link para redefinir sua senha e para concluir o processo acesse: 
http://localhost/teste/recuperar/redefinir/9e56ab9362e5848f5e31467d4739287d8188a96e792a4def2024e0b4627012b4609e116c7670502b110f88e527b0d3118447fb47d3de64e8ccb6a335ac6a92cc 
Atenciosamente,
" } 
string(5) "SIGEP" 
string(28) "sigep.service.mail@gmail.com" 
bool(false) `

**Comment by brunosantoshx** [comment]
Olá @vandersonfabio, tudo bem?

O serviço de e-mail nativo do framework é bem básico e praticamente depende da função `mail`. O que ocorre é que em ambiente local só é possível disparar o e-mail desde que o SMTP esteja devidamente configurado (não vem por padrão).

É comum o `false` como retorno da função `mail` em ambiente local por conta disto. Agora em um ambiente remoto devidamente configurado é bem improvável e se retornar é importante acionar o suporte da hospedagem para entender o que está acontecendo. 

Forte abraço e sucesso sempre!
